### ISSUE TITLE
Forwarding emails?

### ISSUE THREAD

**Issue by bpavacic** [adaline/dockermail#27]
Hello,

I would like to automatically forward emails sent to some accounts to their @gmail accounts, while storing them in on the server for others (like they are stored now).
Would it be possible to add such feature to dockermail-core ?

**Comment by adaline** [comment]
Hey Boris,
I think its possible to do at the moment, please try it out and let me know if it works.

If your domain is `example.com` and your email is `info@example.com`, you want to forward to `forward_to@gmail.com` then the basic config should be like this:

```
{
  "settings": {
    "myhostname": "example.com"
  },
  "domains": {
    "example.com" :
      [
        {
          "email": "info@example.com forward_to@gmail.com",
          "aliases": ["info@example.com"]
        },
        {
          "email": "info@example.com",
          "password": "{SHA256-CRYPT}$5$ojXGqoxOAygN91er$VQD/8dDyCYOaLl2yLJlRFXgl.NSrB3seZGXBRMdZAr6"
        }
      ]
  }
}
````

**Comment by bpavacic** [comment]
It seems to be working! Thanks
It would be nice to add it to the documentation though

**Comment by hheimbuerger** [comment]
@bpavacic I would recommend to closely check your logs. I did this for a while, but the issue was around spam and SPF.

The first problem was that redirecting spam to Gmail (which due to the lack of SRS in dockermail looked to them like it was coming from my server) would quickly put me on their watch list and often cause emails to be delayed. They never completely blacklisted me (rejecting even legitimate mail), but I was worried that eventually they would.
Then again, I wasn't running amavis, so if you do, that might alleviate the issue a little bit.

The other issue (and probably adding to the first problem) was that due to the lack of SRS, this forwarding would break all SPF checks (and I think DKIM, too). Because to Gmail, it seemed like the mail was originating from my server as opposed to the real sender.

I made an attempt to implement SRS for dockermail (see the branch [implement-srs-container](https://github.com/hheimbuerger/dockermail/tree/implement-srs-container) on my fork with the commit https://github.com/hheimbuerger/dockermail/commit/c000cdd82681dc28372174d8e5750791b058ff90) but eventually this became too complex for my liking (my original intent in using dockermail was to be *less* involved in running a mail server, because I really don't know enough to do this properly).

**Comment by adaline** [comment]
Thank you for great info Henrik! I have not tried automatically forwarding my email from dockermail before so have not come across the issues you describe. If many people use it - i will build an SRS component to help people with this setup.

Boris let me know how it goes, I have not used this kind of setup so never considered documenting it. Seeing as you and Henrik have the same needs for forwarding I have added a Wiki page to help anyone else trying to set it up: https://github.com/adaline/dockermail/wiki/Forwarding-email

Thank you both :+1:
